
""""Запрос от API может возвращать код фотографии, соответствующей погоде,
Записав каждый код в ключ словаря можно обращаться к id соответствующей фотографии
Таким образом можно собрать все коды и id соответствующих фото в словарь"""

photosList = [{
    "01d": "AgACAgIAAxkBAAIDWGYHDbKh8K88IY7tafNbrmSG40uUAALo3zEbDUc5SOE1xkpDV0jmAQADAgADeAADNAQ",
    "01n": "AgACAgIAAxkBAAIDWmYHDbbQEHeFfcrYU1_WIlCVXGF3AALp3zEbDUc5SAFFGUyWFBbeAQADAgADeAADNAQ",
    "02d": "AgACAgIAAxkBAAIDXGYHDblvvu-gmfy2gb2Dy4xVJcMBAALq3zEbDUc5SMOu8FsVJRUoAQADAgADeAADNAQ",
    "02n": "AgACAgIAAxkBAAIDXmYHDb2JQ85U11KHqPznSKGKgJ5hAALr3zEbDUc5SAIxkzvNMf17AQADAgADeAADNAQ",
    "03d": "AgACAgIAAxkBAAIDYGYHDb_nuxWpIipRlDA7z7pgc2ZAAALs3zEbDUc5SONv9fCinBMOAQADAgADeAADNAQ",
    "03n": "AgACAgIAAxkBAAIDYGYHDb_nuxWpIipRlDA7z7pgc2ZAAALs3zEbDUc5SONv9fCinBMOAQADAgADeAADNAQ",
    "04d": "AgACAgIAAxkBAAIDYmYHDcX04VDqonOEIUf_TJRhJFIhAALt3zEbDUc5SMPRT9bgU5lUAQADAgADeAADNAQ",
    "04n": "AgACAgIAAxkBAAIDYmYHDcX04VDqonOEIUf_TJRhJFIhAALt3zEbDUc5SMPRT9bgU5lUAQADAgADeAADNAQ",
    "09d": "AgACAgIAAxkBAAIDZGYHDctotFWI3VRnttjc9aI4mf5lAALu3zEbDUc5SBRrmnTym1aiAQADAgADeAADNAQ",
    "09n": "AgACAgIAAxkBAAIDZGYHDctotFWI3VRnttjc9aI4mf5lAALu3zEbDUc5SBRrmnTym1aiAQADAgADeAADNAQ",
    "10d": "AgACAgIAAxkBAAIDZmYHDc3m5gQh4BnY4ymOkV9RhLgJAALv3zEbDUc5SBUPi4KkxMQXAQADAgADeAADNAQ",
    "10n": "AgACAgIAAxkBAAIDZmYHDc3m5gQh4BnY4ymOkV9RhLgJAALv3zEbDUc5SBUPi4KkxMQXAQADAgADeAADNAQ",
    "11d": "AgACAgIAAxkBAAIDaGYHDdBHrxS0dxdx9FBgC26qGGIJAALx3zEbDUc5SKTRcTf95g2RAQADAgADeAADNAQ",
    "11n": "AgACAgIAAxkBAAIDaGYHDdBHrxS0dxdx9FBgC26qGGIJAALx3zEbDUc5SKTRcTf95g2RAQADAgADeAADNAQ",
    "13d": "AgACAgIAAxkBAAIDamYHDdIkEKvKypHsWZzNG81PEXoiAALy3zEbDUc5SLQTJgAB9Jj6BgEAAwIAA3gAAzQE",
    "13n": "AgACAgIAAxkBAAIDamYHDdIkEKvKypHsWZzNG81PEXoiAALy3zEbDUc5SLQTJgAB9Jj6BgEAAwIAA3gAAzQE",
    "50d": "AgACAgIAAxkBAAIDbGYHDdV2sSgxb-M-hukXMog1cvpMAALz3zEbDUc5SC5wkQ6OyjXMAQADAgADeAADNAQ",
    "50n": "AgACAgIAAxkBAAIDbmYHDdhRqX0P8K4tPE0L-Njum_2YAAL03zEbDUc5SAXdkZ2xltXtAQADAgADeAADNAQ",
}]
